Seminar 05 Fitting and interpreting linear models (low volume)
========================================================



```{r}
library(lattice)
library(ggplot2)
prDat <- read.table("GSE4051_data.tsv")
str(prDat, max.level=0)
prDes <- readRDS("GSE4051_design.rds")
str(prDes)
```

```{r}
prepareData <- function(myGenes) {
    miniDat <- t(prDat[myGenes, ])
    miniDat <- suppressWarnings(data.frame(gExp = as.vector(miniDat),
                          gene = rep(colnames(miniDat), each = nrow(miniDat))))
    miniDat <- suppressWarnings(data.frame(prDes, miniDat))
    miniDat
}
```

```{r}
(luckyGenes <- c("1419655_at","1438815_at"))
jDat <- prepareData(luckyGenes)
str(jDat)
head(jDat)
tail(jDat)
summary(jDat)
```

Stripplot
```{r}
stripplot(gExp ~ devStage | gene, jDat,
          group = gType, jitter.data = TRUE,
          auto.key = TRUE, type = c('p', 'a'), grid = TRUE)
```

```{r}
makeStripplot <- function(myData, ...) {
  stripplot(gExp ~ devStage | gene, myData,
            group = gType, jitter.data = TRUE,
            auto.key = TRUE, type = c('p', 'a'), grid = TRUE, ...)
}
```

```{r}
makeStripplot(jDat)
makeStripplot(jDat, pch = 17, cex = 3)
```


```{r}
makeStripplot(newDat <- prepareData("1456341_a_at"))
str(newDat)
head(newDat)
```

```{r}
t.test(gExp ~ devStage, newDat,
       subset = devStage %in% c("P2", "4_weeks"),
       var.equal = TRUE)
```


```{r}
makeStripplot(mDat <- prepareData("1438786_a_at"))
```

```{r}
mFit <- lm(gExp~devStage, mDat, subset=gType=="wt")
summary(mFit)
```

```{r}
coef(mFit)
```

```{r}
contMat <- matrix(c(0, 1, 0, -1, 0), nrow = 1)
```

```{r}
(obsDiff <- contMat %*% coef(mFit))
```

```{r}
(sampMeans <- aggregate(gExp ~ devStage, mDat, FUN = mean, subset = gType == "wt"))
with(sampMeans, gExp[devStage == "P2"] - gExp[devStage == "P10"])
```

```{r}
vcov(mFit)
summary(mFit)$coefficients[ , "Std. Error"]
sqrt(diag(vcov(mFit)))
summary(mFit)$coefficients
```

```{r}
(estSe <- contMat %*% vcov(mFit) %*% t(contMat))
(testStat <- obsDiff/estSe)
2 * pt(abs(testStat), df = df.residual(mFit), lower.tail = FALSE)
```

```{r}
makeStripplot(oDat <- prepareData("1448690_at"))
str(oDat)
```

```{r}
oFitBig <- lm(gExp ~ gType * devStage, oDat)
summary(oFitBig)$coef
```

```{r}
oFitSmall <- lm(gExp~gType+devStage, oDat)
summary(oFitSmall)$coef
```

```{r}
anova(oFitSmall, oFitBig)
```


```{r}
makeStripplot(pDat <- prepareData("1429225_at"), cex = 2)
pFitBig <- lm(gExp ~ gType * devStage, pDat)
summary(pFitBig)$coef
pFitSmall <- lm(gExp ~ gType + devStage, pDat)
summary(pFitSmall)$coef
anova(pFitSmall, pFitBig)
```
