

seminar 04
===============================================


```{r}
library(lattice)
library(ggplot2)
prDat <- read.table("GSE4051_data.tsv")
str(prDat, max.level = 0)

```

```{r}
prDes <- readRDS("GSE4051_design.rds")
str(prDes)
```
```{r}
set.seed(987)
(theGene <- sample(1:nrow(prDat),1))
```
```{r}
pDat <- data.frame(prDes, gExp = unlist(prDat[theGene, ]))
str(pDat)
```
```{r}
aggregate(gExp ~ gType, pDat, FUN = mean)
```
```{r}
stripplot(gType ~ gExp, pDat)
```

```{r}
ggplot(pDat, aes(x=gExp, y=gType))+geom_point()
```
T-test comparing wild type to the Nrl knockouts
```{r}
t.test(gExp~gType, pDat)
```
save the t test result

```{r}
ttRes <- t.test(gExp~gType, pDat)
str(ttRes)
```

```{r}
ttRes$statistic
ttRes$p.value
```

```{r}
kDat <- readRDS("GSE4051_MINI.rds")
kMat <- as.matrix(kDat[c('crabHammer','eggBomb','poisonFang')])
str(kMat)
class(kMat)
```
Compute the median
```{r}
median(kMat[,1])
median(kMat[,'eggBomb'])
apply(kMat,2,median)
```

```{r}
apply(kMat,2,quantile,probs=c(0.25,0.5))
apply(kMat,1,min)
colnames(kMat)[apply(kMat,1,which.min)]
rowSums(kMat)
rowMeans(kMat)
all.equal(rowSums(kMat),apply(kMat,1,sum))
```

```{r}
aggregate(eggBomb~devStage, kDat, FUN=mean)
aggregate(eggBomb~gType*devStage, kDat, FUN=mean)
aggregate(eggBomb~gType*devStage, kDat, FUN=range)
```
revisiting with plyr
```{r}
ddply(kDat, ~ devStage, summarize, avg = mean(eggBomb))
ddply(kDat, ~ gType * devStage, summarize, avg = mean(eggBomb))
ddply(kDat, ~ gType * devStage, summarize,
      min = min(eggBomb), max = max(eggBomb))
```
Two sample tests
===============================================
```{r}
keepGenes <- c("1431708_a_at", "1424336_at", "1454696_at","1416119_at", "1432141_x_at", "1429226_at" )
miniDat <- subset(prDat, rownames(prDat)%in% keepGenes)
str(miniDat)

miniDat <- data.frame(gExp = as.vector(t(as.matrix(miniDat))),gene = factor(rep(rownames(miniDat), each = ncol(miniDat)),levels = keepGenes))

miniDat <- suppressWarnings(data.frame(prDes,miniDat))
str(miniDat)
```
Lattice
```{r}
stripplot(gType ~ gExp|gene, miniDat, scales= list(x=list(relation="free")), group=gType, auto.key=TRUE)
```
GGPLOT2
```{r}
ggplot(miniDat, aes(x = gExp, y = gType, color = gType)) +
  facet_wrap(~ gene, scales="free_x") +
  geom_point(alpha = 0.7) +
  theme(panel.grid.major.x = element_blank())
```

```{r}
someDat <- droplevels(subset(miniDat, gene == keepGenes[1]))

t.test(gExp ~ gType, someDat)
```

```{r}
library(plyr)
d_ply(miniDat, ~ gene, function(x) t.test(gExp ~ gType, x), .print = TRUE)
```

```{r}
ttRes <- dlply(miniDat, ~ gene, function(x) t.test(gExp ~ gType, x))
names(ttRes)
```

```{r}
ttRes[["1431708_a_at"]]
```
The core of t-test
```{r}
ttRes <- ddply(miniDat, ~ gene, function(z) {
  zz <- t.test(gExp ~ gType, z)
  round(c(tStat = zz$statistic, pVal = zz$p.value), 4)
})
ttRes
```
