prDat <- read.table("GSE4051_MINI.txt", header = TRUE, row.names = 1)
str(prDat)
nrow(prDat)
dim(prDat)
length(prDat)
head(prDat)
names(prDat)
prDat
summary(prDat)
with(prDat,table(devStage,gType))
min(prDat$crabHammer)
max(prDat$crabHammer)
range(prDat$crabHammer)
summary(prDat$crabHammer)
fivenum(prDat$crabHammer)
weeDat <- subset(prDat,poisonFang>7.5)
nrow(weeDat)
table(weeDat$gType)
table(weeDat$devStage)
addmargins(with(weeDat, table(devStage, gType)))
prDat[c("Sample_16", "Sample_38"), c("crabHammer", "eggBomb", "poisonFang")]
rownames(prDat[prDat$eggBomb < quantile(prDat$eggBomb, 0.1), ])
