Seminar 06
========================================================
```{r}
source("http://www.bioconductor.org/biocLite.R")
biocLite("limma")
biocLite("statmod")
```

To load limma, lattice and ggplot2.
```{r}
library(limma)
library(lattice)
library(ggplot2)
```


```{r}
prDat <- read.table("GSE4051_data.tsv")
str(prDat, max.level = 0)
prDes <- readRDS("GSE4051_design.rds")
str(prDes)
```

DIY funtions
```{r}
prepareData <- function(myGenes) {
    miniDat <- t(wtDat[myGenes, ])
    miniDat <- data.frame(gExp = as.vector(miniDat),
                          gene = factor(rep(colnames(miniDat), each =
                          nrow(miniDat)), levels = colnames(miniDat)))
    miniDat <- suppressWarnings(data.frame(wtDes, miniDat))
    miniDat
}
stripplotIt <- function(myData, ...) {
    stripplot(gExp ~ devStage | gene, myData,
              jitter.data = TRUE,
              auto.key = TRUE, type = c('p', 'a'), grid = TRUE, ...)
}
```

Simulation
```{r}
m <- 1000
n <- 3
x <- matrix(rnorm(m*n), nrow=m)
  
```

```{r}
obsVars <- apply(x,1,var)
summary(obsVars)
mean(obsVars < 1/3)
densityplot(~obsVars, n=200)
```

ANOVA
```{r}
wtDes <- subset(prDes, gType == "wt")
str(wtDes)
wtDat <- subset(prDat, select = prDes$gType == "wt")
str(wtDat, max.level = 0)
```


```{r}
wtDesMat <- model.matrix(~devStage, wtDes)
str(wtDesMat)
```


```{r}
wtFit <- lmFit(wtDat,wtDesMat)
wtEbFit <- eBayes(wtFit)
```


```{r}
topTable(wtEbFit)
topTable(wtEbFit, coef = 2:5)
colnames(coef(wtEbFit))
(dsHits <- topTable(wtEbFit, coef = grep("devStage", colnames(coef(wtEbFit)))))
```


```{r}
stripplotIt(prepareData(rownames(dsHits)[c(3,6,9)]))
```


```{r}
cutoff <- 1e-05
dsHits <- topTable(wtEbFit,coef = grep("devStage", colnames(coef(wtEbFit))),p.value = cutoff, n = Inf)
(numBHhits <- nrow(dsHits))
```


```{r}
dsHits[63, c("F", "adj.P.Val", "devStageP6")]
```

```{r}
P2Hits <- topTable(wtEbFit, coef = "devStageP2", n = Inf, sort = "none")
P10Hits <- topTable(wtEbFit, coef = "devStageP10", n = Inf, sort = "none")
xyplot(P10Hits$t ~ P2Hits$t, aspect = 1,
       xlab = "t-statistic for P2 effect",
       ylab = "t-statistic for P10 effect",
       xlim = c(-20, 16), ylim = c(-20, 16),
       panel = function(x, y, ...) {
         panel.smoothScatter(x, y, nbin = 100, ...)
         panel.abline(a = 0, b = 1, col = "orange")
})
```

```{r}
densityplot(~ P10Hits$adj.P.Val + P2Hits$adj.P.Val, auto.key = TRUE,
            plot.points = FALSE, n = 300)
```

```{r}
cutoff <- 1e-03
foo <- data.frame(P2 = P2Hits$adj.P.Val < cutoff,
                  P10 = P10Hits$adj.P.Val < cutoff)
addmargins(with(foo, table(P2, P10)))
```

```{r}
P10pVals <- data.frame(raw = P10Hits$P.Value,
                       BH = P10Hits$adj.P.Val,
                       BY = p.adjust(P10Hits$P.Value, method = "BY"))
splom(P10pVals,
      panel = function(x, y, ... ) {
          panel.xyplot(x, y, pch = ".", ...)
          panel.abline(a = 0, b = 1, col = "orange")
      })
```

```{r}
colnames(wtDesMat)
(cont.matrix <- makeContrasts(P10VsP6 = devStageP10 - devStageP6, fourweeksVsP10 = devStage4_weeks - 
    devStageP10, levels = wtDesMat))

```

```{r}
wtFitCont <- contrasts.fit(wtFit, cont.matrix)
wtEbFitCont <- eBayes(wtFitCont)
```


```{r}
topTable(wtEbFitCont)

```

```{r}
foo <- topTable(wtEbFitCont)
stripplotIt(prepareData(rownames(foo)[1:4]))

```


```{r}
cutoff <- 1e-04
wtResCont <- decideTests(wtEbFitCont, p.value = cutoff, method = "global")
summary(wtResCont)

```

```{r}
(hits1 <- rownames(prDat)[which(wtResCont[, "P10VsP6"] < 0)])
stripplotIt(prepareData(hits1))
```

```{r}
(hits2 <- rownames(prDat)[which(wtResCont[,"fourweeksVsP10"]<0)])
stripplotIt(prepareData(hits2[1:4]))
```



```{r}
intersect(hits1, hits2)

```



```{r}
(hits3 <- rownames(prDat)[which(wtResCont[, "fourweeksVsP10"] > 0)])
stripplotIt(prepareData(hits3[1:4]))
```



```{r}
intersect(hits1, hits3)
intersect(hits2, hits3)

```



```{r}
cutoff <- 0.01
nHits <- 8
wtResCont <- decideTests(wtEbFitCont, p.value = cutoff, method = "global")
summary(wtResCont)
hits1 <- rownames(prDat)[which(wtResCont[, "P10VsP6"] < 0)]
stripplotIt(prepareData(hits1[1:nHits]))
hits2 <- rownames(prDat)[which(wtResCont[, "fourweeksVsP10"] < 0)]
stripplotIt(prepareData(hits2[1:nHits]))
hits3 <- rownames(prDat)[which(wtResCont[, "P10VsP6"] > 0)]
stripplotIt(prepareData(hits3[1:nHits]))
hits4 <- rownames(prDat)[which(wtResCont[, "fourweeksVsP10"] > 0)]
stripplotIt(prepareData(hits4[1:nHits]))
vennDiagram(wtResCont)
hits5 <- rownames(prDat)[which(wtResCont[, "P10VsP6"] != 0 &
                                  wtResCont[, "fourweeksVsP10"] != 0)]
stripplotIt(prepareData(hits5))
hits6 <- rownames(prDat)[which(wtResCont[, "P10VsP6"] > 0 &
                                  wtResCont[, "fourweeksVsP10"] < 0)]
stripplotIt(prepareData(hits6))
```



```{r}
lateStuff <- topTable(wtEbFitCont, n = Inf, sort = "none")
earlyStuff <- topTable(wtEbFit,
                       coef = grep("devStageP[26]", colnames(coef(wtEbFit))),
                       n = Inf, sort = "none")
pVals <-
  data.frame(earlyStuff = earlyStuff$adj.P.Val,
             lateStuff = lateStuff$adj.P.Val)
xyplot(lateStuff ~ earlyStuff, pVals)
discHits <- with(pVals,
     which(earlyStuff < quantile(earlyStuff, probs = 0.05) &
             lateStuff > quantile(lateStuff, probs = 0.95)))
length(discHits)
set.seed(123)
stripplotIt(prepareData(miniDat <- sample(discHits, 6)),
            scales = list(y = list(relation = "free")))

```


```{r}


```
